networks:
  performance-testing-cluster:
    name: performance-testing-cluster
    external: true
    driver: overlay

services:
  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper-2
    restart: always
    networks:
      - performance-testing-cluster
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_MY_ID: 2
    ports:
      - "32181:2181"

  perf-B:
    hostname: perf-B
    container_name: perf-B
    networks:
      - performance-testing-cluster
    image: confluentinc/cp-kafka:latest
    ports:
      - "9082:9082"
      - "29082:29082"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://perf-B:9082
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


